org: guy1812
app: wix-auth
service: wix-auth-test

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1
  apiKeys:
    - serverless_wix${self:provider.stage}
  tracing:
    apiGateway: true
    lambda: true

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  serverless-offline:
    httpPort: 4000

functions:
  wixAuth:
    handler: src/functions/Wix/Authentication.sendWixOAuth
    events:
      - http:
          path: wix/authentication
          method: post
          private: false
          cors: true
